name: Android Pull Request Sanity Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: step_0_checkout
        uses: actions/checkout@v3.3.0
      - name: step_1_assembleProdDebug
        run: ./gradlew :app:assembleProdDebug
      - name: step_2_generateCoverageReport
        run: ./gradlew rootCoverageReport -Penable_android_test=false -Penable_unit_test=true -Pcoverage
